### ISSUE TITLE
Nested conditionals / loops unsupported

### ISSUE THREAD

**Issue by LegionMammal978** [olls/3var-interpreter#1]
Conditionals and loops' code only searches for the corresponding opening or closing character. This would break programs such as `iiaa+>aaa=(k=($ 2 + 2 = 4 and 2 + 2 = 5 $)$ 2 + 2 != 4 and 2 + 2 = 5 $)$ 2 + 2 != 5 $`, where the interpreter selects the first `)` and breaks logic.

**Comment by olls** [comment]
Yep, It's a very simple implementation, it was one of the first C programs I wrote. I might add proper recursive block parsing at some point... Feel free to submit a pull request if you feel like fixing it :)
